var  firstName ="Javascript";
var companyName="Apple" ;
var mobileNumber ="123456899" ;
var isAutomation=true  ;   
var hasPlaywright ; 
console.log(firstName);
console.log(typeof firstName);
console.log(companyName);
console.log(typeof companyName);
console.log(mobileNumber);
console.log(typeof mobileNumber);
console.log(isAutomation);
console.log(typeof isAutomation);
console.log(hasPlaywright);
console.log(typeof hasPlaywright);